class NotFoundError(Exception):
    pass


class ConflictError(Exception):
    pass
